server:
  port: ${PORT:8020}

logging.level:
  ch.globaz.tmmas: TRACE
  org.springframework.web.servlet.mvc.support: TRACE

elasticsearch:
  hosts:
    - http://localhost:9200
  connectTimeout: 10000
  connectionRequestTimeout: 10000
  socketTimeout: 10000
  maxRetryTimeoutMillis: 60000

spring.metrics.export.graphite:
  host: localhost
  port: 2010
  protocol: Plaintext
  step: PT1S

# disable beans endpoint
management.endpoints.beans.enabled: false
# expose all endpoints:
management.endpoints.web.exposure.include: "*"